export const MODIFIER_KEYS = new Set(["meta", "ctrl", "control", "alt", "shift"]);

export const STANDALONE_MODIFIERS = new Set([
  "Command",
  "Control",
  "Alt",
  "Shift",
]);

export const KEY_MAP: Record<string, string> = {
  escape: "Escape",
  enter: "Enter",
  tab: "Tab",
  space: "Space",
  backspace: "Backspace",
  delete: "Delete",
  home: "Home",
  end: "End",
  pageup: "PageUp",
  pagedown: "PageDown",
  insert: "Insert",
  arrowup: "ArrowUp",
  arrowdown: "ArrowDown",
  arrowleft: "ArrowLeft",
  arrowright: "ArrowRight",
  comma: "Comma",
  period: "Period",
  slash: "Slash",
  semicolon: "Semicolon",
  quote: "Quote",
  minus: "Minus",
  equal: "Equal",
  bracketleft: "BracketLeft",
  bracketright: "BracketRight",
  backslash: "Backslash",
  backquote: "Backquote",
};

export const DISPLAY_MAP: Record<string, string> = {
  Command: "\u2318",
  CommandOrControl: "\u2318/\u2303",
  CommandOrCtrl: "\u2318/\u2303",
  CmdOrCtrl: "\u2318/\u2303",
  Control: "\u2303",
  Ctrl: "\u2303",
  Alt: "\u2325",
  Shift: "\u21E7",
  Super: "Super",
  Meta: "Meta",
  Space: "Space",
  Escape: "\u238B",
  Enter: "\u21A9",
  Backspace: "\u232B",
  Delete: "\u2326",
  Tab: "\u21E5",
  ArrowUp: "\u2191",
  ArrowDown: "\u2193",
  ArrowLeft: "\u2190",
  ArrowRight: "\u2192",
  PageUp: "\u21DE",
  PageDown: "\u21DF",
};
